packages:
  - "spec"
  - "integration/js/fastify/openws"
  - "integration/js/fastify/openws-spec"
  - "integration/js/polytric"
  - "tooling/sdkgen/dotnet/runtime/io.polytric.openwssdk.core"
  - "tooling/sdkgen/dotnet/runtime/io.polytric.openwssdk.unity"
  - "tooling/sdkgen/dotnet/test/Testbed/Assets"

  # Ignore Unity files
  - "!**/Library/**"
  - "!**/Temp/**"
  - "!**/Obj/**"
  - "!**/Build/**"
  - "!**/PackageCache/**"
  - "!**/dotnet/test/OpenWsTestBed/**"
