packages:
    - 'integration/csharp/io.polytric.openws.core'
    - 'integration/csharp/io.polytric.openws.spec'
    - 'integration/csharp/io.polytric.openws.unity'
    - 'integration/js/fastify-openws-ui'
    - 'integration/js/fastify-openws'
    - 'integration/js/openws-ui'
    - 'integration/js/openws'
    - 'spec'
    - 'tooling/sdkgen'
    - 'tooling/sdkgen/dotnet/test/UnityTestbed'

    # Ignore Unity files
    - '!**/Library/**'
    - '!**/Temp/**'
    - '!**/Obj/**'
    - '!**/Build/**'
    - '!**/PackageCache/**'
    - '!**/dotnet/test/OpenWsTestBed/**'
